services:
  figth:
    image: rinha-spring
    container_name: service_1
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/figth_db
      - DB_USER=figth_user
      - DB_PASSWORD=figth_password
      - PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - figth-network
      - payment-processor

  postgres:
    image: postgres:17-alpine
    container_name: figth-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: figth_db
      POSTGRES_USER: figth_user
      POSTGRES_PASSWORD: figth_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-collate=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - figth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U figth_user -d figth_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 180M
        reservations:
          cpus: '0.4'
          memory: 140M

volumes:
  postgres_data:
    driver: local

networks:
  figth-network:
    driver: bridge
  payment-processor:
    external: true 