services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-boot-figth
    networks:
      - figth-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 30M
        reservations:
          cpus: '0.05'
          memory: 20M
  spring-boot-figth:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    container_name: spring-boot-figth
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=figth-postgres
      - DB_PORT=5432
      - DB_NAME=figth_db
      - DB_USER=figth_user
      - DB_PASSWORD=figth_password
      - PAYMENT_PROCESSOR_HOST=payment-processor-default
      - PAYMENT_PROCESSOR_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - figth-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 130M
        reservations:
          cpus: '0.5'
          memory: 100M
  postgres:
    image: postgres:17-alpine
    container_name: figth-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: figth_db
      POSTGRES_USER: figth_user
      POSTGRES_PASSWORD: figth_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - figth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U figth_user -d figth_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 180M
        reservations:
          cpus: '0.4'
          memory: 140M

volumes:
  postgres_data:
    driver: local

networks:
  figth-network:
    driver: bridge
  payment-processor:
    external: true 