spring:
  application:
    name: figth
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

logging:
  level:
    com.backend.figth: INFO

# Configuração do Payment Processor
payment:
  processor:
    url: ${PAYMENT_PROCESSOR_URL}